# Generated by Django 2.1.1 on 2019-06-07 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyDetails',
            fields=[
                ('county_name', models.CharField(max_length=30)),
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_name', models.CharField(max_length=20)),
                ('equipment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_name', models.CharField(max_length=30)),
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric or contain numbers', regex='^[a-zA-Z0-9.+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('employer', models.ManyToManyField(to='Cleaner.Employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=30)),
                ('receiver', models.ForeignKey(on_delete=True, to='Cleaner.MyUser')),
                ('sender', models.ForeignKey(on_delete=True, to='Cleaner.Employer')),
            ],
        ),
    ]
